# Generated by Django 5.0.8 on 2024-11-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='uploads/products/default.jpg', upload_to='uploads/products/'),
        ),
    ]
