apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Checkout repository
        uses: docker://alpine/git
        shell: sh
        run: |
          git clone https://github.com/jalts-808/d.git .

      - name: Set up Python environment
        uses: docker://python:3.12
        shell: sh
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        uses: docker://python:3.12
        shell: sh
        run: |
          . venv/bin/activate
          cd ecom
          python manage.py migrate

      - name: Collect static files
        uses: docker://python:3.12
        shell: sh
        run: |
          . venv/bin/activate
          cd ecom
          python manage.py collectstatic --noinput

      - name: Run tests and collect results
        uses: docker://python:3.12
        shell: sh
        continue-on-error: true
        run: |
          . venv/bin/activate
          cd ecom
          pytest --maxfail=5 --disable-warnings --junitxml=/workspace/test-results.xml
          ls -l /workspace  # Verify test-results.xml exists

      - name: Publish test results to CloudBees
        action: test-result-collector  # Explicitly define the test action
        with:
          format: junit
          path: /workspace/test-results.xml
