apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Checkout repository
        uses: docker://alpine/git
        shell: sh
        run: |
          git clone https://github.com/jalts-808/d.git .

      - name: Set up Python environment
        uses: docker://python:3.12
        shell: sh
        run: |
          python -m venv /workspace/venv
          . /workspace/venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install + Verify Launchable CLI
        uses: docker://python:3.12
        shell: sh
        env:
          LAUNCHABLE_TOKEN: ${{ secrets.LaunchableToken }}
        run: |
          apt-get update
          apt-get install -y default-jre git
          git config --global --add safe.directory /cloudbees/workspace
          . /workspace/venv/bin/activate
          pip install --upgrade launchable~=1.0
          launchable verify || true

      - name: Run migrations
        uses: docker://python:3.12
        shell: sh
        run: |
          . /workspace/venv/bin/activate
          cd ecom
          python manage.py migrate

      - name: Collect static files
        uses: docker://python:3.12
        shell: sh
        run: |
          . /workspace/venv/bin/activate
          cd ecom
          python manage.py collectstatic --noinput

      - name: Run tests and record them
        uses: docker://python:3.12
        shell: sh
        continue-on-error: true
        env:
          LAUNCHABLE_TOKEN: ${{ secrets.LaunchableToken }}
        run: |
          apt-get update
          apt-get install -y default-jre git
          git config --global --add safe.directory /cloudbees/workspace

          . /workspace/venv/bin/activate
          cd ecom

          # DO NOT DO: launchable record build … 
          # because older CLI can’t link test results to that build anyway

          pytest || true

          ls -l /workspace

          # Record test results with no build, using raw
          # => no conflict, no .launchable file
          launchable record tests --no-build raw /workspace/test-results.xml || true


      - name: Publish test results
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: JUnit
          folder-name: /workspace/test-results.xml
