apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    environment: |
      export LAUNCHABLE_TOKEN="${{ properties.LaunchableToken }}"
      # Add as many export lines as you want

    steps:
      - name: Checkout repository
        uses: docker://alpine/git
        shell: sh
        run: |
          git clone https://github.com/jalts-808/d.git .

      - name: Set up Python environment
        uses: docker://python:3.12
        shell: sh
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Launchable CLI
        uses: docker://python:3.12
        shell: sh
        run: |
          pip install --user --upgrade launchable~=1.0

      - name: Verify Launchable CLI
        uses: docker://python:3.12
        shell: sh
        run: |
          launchable verify || true

      - name: Run migrations
        uses: docker://python:3.12
        shell: sh
        run: |
          . venv/bin/activate
          cd ecom
          python manage.py migrate

      - name: Collect static files
        uses: docker://python:3.12
        shell: sh
        run: |
          . venv/bin/activate
          cd ecom
          python manage.py collectstatic --noinput

      - name: Run tests with Launchable session
        uses: docker://python:3.12
        shell: sh
        continue-on-error: true
        run: |
          . venv/bin/activate
          cd ecom
          launchable record build --source . --name "$(git rev-parse HEAD)"
          launchable record session pytest --name "$(date +%s)"
          pytest --maxfail=5 --disable-warnings --junitxml=/workspace/test-results.xml
          ls -l /workspace

      - name: Publish test results
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: JUnit
          folder-name: /workspace/test-results.xml