apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Checkout repository
        uses: docker://alpine/git
        shell: sh
        run: |
          git clone https://github.com/jalts-808/d.git .

      - name: Set up Python environment
        uses: docker://python:3.12
        shell: sh
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        uses: docker://python:3.12
        shell: sh
        run: |
          . venv/bin/activate
          cd ecom
          python manage.py migrate
          ls -l db.sqlite3  # Verify that the SQLite database is created

      - name: Collect static files
        uses: docker://python:3.12
        shell: sh
        run: |
          . venv/bin/activate
          cd ecom
          python manage.py collectstatic --noinput
          ls -l staticfiles  # Verify static files are collected

      - name: Run tests
        uses: docker://python:3.12
        shell: sh
        run: |
          . venv/bin/activate
          cd ecom
          pytest --maxfail=5 --disable-warnings --junitxml=/workspace/test-results.xml
          ls -l /workspace  # Verify that the test-results.xml file is generated

      - name: Publish test results
        uses: docker://cloudbees/test-results:latest
        shell: sh
        run: |
          ls -l /workspace  # Confirm test-results.xml exists
          /cloudbees/test-results/publish --path /workspace/test-results.xml --format junit

      - name: Debug test results
        uses: docker://alpine
        shell: sh
        run: |
          ls -l /workspace  # Final debug to ensure files are in place
