apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Checkout repository
        uses: docker://alpine/git
        shell: sh
        run: |
          git clone https://github.com/jalts-808/d.git .

      - name: Set up Python environment
        uses: docker://python:3.12
        shell: sh
        run: |
          python -m venv /workspace/venv
          . /workspace/venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with Launchable session
        uses: docker://python:3.12
        shell: sh
        continue-on-error: true
        env:
          LAUNCHABLE_TOKEN: ${{ secrets.LaunchableToken }}
        run: |
          apt-get update
          apt-get install -y default-jre git
          git config --global --add safe.directory /cloudbees/workspace

          . /workspace/venv/bin/activate
          cd ecom

          # Record a build
          launchable record build --source . --name "$(git rev-parse HEAD)"

          # **Use '--' to separate Launchable's flags from Pytest's flags**
          launchable record session \
            --session-name "$(date +%s)" \
            -- \
            pytest . --maxfail=5 --disable-warnings --junitxml=/workspace/test-results.xml || true

          ls -l /workspace

      - name: Run migrations
        uses: docker://python:3.12
        shell: sh
        run: |
          . /workspace/venv/bin/activate
          cd ecom
          python manage.py migrate

      - name: Collect static files
        uses: docker://python:3.12
        shell: sh
        run: |
          . /workspace/venv/bin/activate
          cd ecom
          python manage.py collectstatic --noinput

      - name: Run tests with Launchable session
        uses: docker://python:3.12
        shell: sh
        continue-on-error: true
        env:
          LAUNCHABLE_TOKEN: ${{ secrets.LaunchableToken }}
        run: |
          apt-get update
          apt-get install -y default-jre git
          git config --global --add safe.directory /cloudbees/workspace

          . /workspace/venv/bin/activate
          cd ecom

          # Record a build
          launchable record build --source . --name "$(git rev-parse HEAD)"

          # Start a test session with the new CLI usage
          # We pass our test runner (pytest) and its arguments after `--`
          launchable record session \
            --session-name "$(date +%s)" \
            pytest -- . --maxfail=5 --disable-warnings --junitxml=/workspace/test-results.xml || true

          # Double-check that test-results.xml exists
          ls -l /workspace

      - name: Publish test results
        uses: cloudbees-io/publish-test-results@v1
        with:
          test-type: JUnit
          folder-name: /workspace/test-results.xml
