apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Install dependencies
        uses: docker://python:3.12
        shell: sh
        run: |
          pip install -r requirements.txt
      - name: Run tests
        uses: docker://python:3.12
        shell: sh
        run: pytest
